app = 'ac-server-monitor'
# app = 'ac-server-monitor-test' # test deployment

primary_region = 'sea'

[build]

[env]
DB_PATH = '/data/monitor.db'
PORT = '8080'

[[mounts]]
source = "acservermonitor_volume"
# source = 'test_acservermonitor_volume' # test deployment
destination = '/data'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[http_service.checks]]
interval = '30s'
timeout = '10s'
grace_period = '15s'
method = 'GET'
path = '/'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[metrics]]
port = 8080
path = '/metrics/'
